---
# yaml-language-server: $schema=https://json.schemastore.org/label-commenter-config.json
# =================================================================================================
# Area Labels
# =================================================================================================
area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

area/terraform:
  - changed-files:
      - any-glob-to-any-file: "*.tf"
      - any-glob-to-any-file: "modules/**/*"

# =================================================================================================
# Device Labels
# =================================================================================================
device/RB5009:
  - changed-files:
      - any-glob-to-any-file: "modules/rb5009/**/*"

device/CRS326:
  - changed-files:
      - any-glob-to-any-file: "modules/crs326/**/*"

device/CRS317:
  - changed-files:
      - any-glob-to-any-file: "modules/crs317/**/*"

device/HEX:
  - changed-files:
      - any-glob-to-any-file: "modules/hex/**/*"
