[tools]
# =================================================================================================
# Project Tools
# =================================================================================================
"aqua:hashicorp/terraform" = "1.14.1"
"aqua:gruntwork-io/terragrunt" = "0.93.12"
"aqua:terraform-linters/tflint" = "0.60.0"

"ubi:go-task/task" = "3"

# =================================================================================================
# CI Tools
# =================================================================================================
"aqua:rhysd/actionlint" = "1"
"npm:@commitlint/cli" = "20"
"pipx:yamllint" = "1"
