---
repos:
  - repo: local
    hooks:
      - id: actionlint
        name: actionlint
        entry: mise exec -- actionlint
        language: system
        files: ^\.github/workflows/.*\.(ya?ml)$
        pass_filenames: false

      - id: yamllint
        name: yamllint
        entry: mise exec -- yamllint -c .yamllint.yaml .
        language: system
        types: [yaml]

      - id: tofu-fmt
        name: tofu format
        entry: mise exec -- tofu fmt -check -recursive
        language: system
        files: \.tf$
        pass_filenames: false

      - id: terragrunt-fmt
        name: terragrunt format
        entry: mise exec -- terragrunt hcl format --check
        language: system
        files: \.hcl$
        pass_filenames: false

  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
